spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/deck-menu_db
    username: user
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create