spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/exo_jwt
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

application:
  jwt:
    header-prefix: "Bearer "
    secret: "8TnBtx7HDLtG0%6j#c4#Mam5Fsq9UkWxBkNy$L^ck#plJ8Ubhs"
    header-key: "Authorization"