spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/nursery_db
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  security:
    user:
      name: user
      password: pass
      roles:
        - USER

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create